### YamlMime:ManagedReference
items:
- uid: EvilDICOM.Anonymization.Settings
  commentId: N:EvilDICOM.Anonymization.Settings
  id: EvilDICOM.Anonymization.Settings
  children:
  - EvilDICOM.Anonymization.Settings.AnonymizationSettings
  - EvilDICOM.Anonymization.Settings.DateSettings
  langs:
  - csharp
  - vb
  name: EvilDICOM.Anonymization.Settings
  nameWithType: EvilDICOM.Anonymization.Settings
  fullName: EvilDICOM.Anonymization.Settings
  type: Namespace
  assemblies:
  - EvilDICOM
references:
- uid: EvilDICOM.Anonymization.Settings.AnonymizationSettings
  commentId: T:EvilDICOM.Anonymization.Settings.AnonymizationSettings
  parent: EvilDICOM.Anonymization.Settings
  name: AnonymizationSettings
  nameWithType: AnonymizationSettings
  fullName: EvilDICOM.Anonymization.Settings.AnonymizationSettings
- uid: EvilDICOM.Anonymization.Settings.DateSettings
  commentId: T:EvilDICOM.Anonymization.Settings.DateSettings
  parent: EvilDICOM.Anonymization.Settings
  name: DateSettings
  nameWithType: DateSettings
  fullName: EvilDICOM.Anonymization.Settings.DateSettings
- uid: EvilDICOM.Anonymization.Settings
  commentId: N:EvilDICOM.Anonymization.Settings
  name: EvilDICOM.Anonymization.Settings
  nameWithType: EvilDICOM.Anonymization.Settings
  fullName: EvilDICOM.Anonymization.Settings
